name: login_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - asset/image/


  fonts:
     - family: SansitaSwashed
       fonts:
         - asset: asset/font/SansitaSwashed-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: oswald
       fonts:
         - asset: asset/font/Oswald-Bold.ttf
     - family: nunito
       fonts:
         - asset: asset/font/Nunito-Bold.ttf
     - family: os
       fonts:
         - asset: asset/font/Oswald-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
